#!/bin/bash
# Gitea Pages Quickstart Test Script
# This script sets up a complete testing environment

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$(dirname "$SCRIPT_DIR")")"

# Use docker compose or docker-compose
if docker compose version &> /dev/null; then
    DOCKER_COMPOSE="docker compose"
elif command -v docker-compose &> /dev/null; then
    DOCKER_COMPOSE="docker-compose"
else
    echo "Error: docker compose not found"
    exit 1
fi

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
log_warning() { echo -e "${YELLOW}[WARNING]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# Check dependencies
check_dependencies() {
    log_info "Checking dependencies..."

    local missing=()

    if ! command -v docker &> /dev/null; then
        missing+=("docker")
    fi

    if ! command -v docker-compose &> /dev/null && ! docker compose version &> /dev/null; then
        missing+=("docker-compose")
    fi

    if ! command -v curl &> /dev/null; then
        missing+=("curl")
    fi

    if ! command -v git &> /dev/null; then
        missing+=("git")
    fi

    if ! command -v jq &> /dev/null; then
        missing+=("jq")
    fi

    if [ ${#missing[@]} -gt 0 ]; then
        log_error "Missing dependencies: ${missing[*]}"
        exit 1
    fi

    log_success "All dependencies found"
}

# Wait for Gitea to be ready
wait_for_gitea() {
    log_info "Waiting for Gitea to be ready..."

    local max_attempts=60
    local attempt=0

    while [ $attempt -lt $max_attempts ]; do
        if curl -sf http://localhost:3000/api/v1/version > /dev/null 2>&1; then
            log_success "Gitea is ready"
            return 0
        fi

        attempt=$((attempt + 1))
        echo -n "."
        sleep 2
    done

    echo ""
    log_error "Gitea failed to start within timeout"
    return 1
}

# Create Gitea user and token
setup_gitea() {
    log_info "Setting up Gitea..."

    # Create admin user (run as git user inside Gitea container)
    log_info "Creating admin user..."
    docker exec -u git gitea-pages-test-gitea gitea admin user create \
        --username testuser \
        --password testpassword123 \
        --email testuser@pages.local \
        --admin \
        --must-change-password=false 2>/dev/null || log_warning "User may already exist"

    # Create access token
    log_info "Creating access token..."
    local token_response
    token_response=$(curl -sf -X POST \
        -H "Content-Type: application/json" \
        -d '{"name": "pages-deployer", "scopes": ["write:repository", "write:admin", "write:user", "write:organization"]}' \
        "http://testuser:testpassword123@localhost:3000/api/v1/users/testuser/tokens" 2>/dev/null)

    if [ -z "$token_response" ]; then
        log_error "Failed to create access token"
        return 1
    fi

    GITEA_TOKEN=$(echo "$token_response" | jq -r '.sha1')
    log_success "Created token: ${GITEA_TOKEN:0:8}..."

    # Save to .env file
    log_info "Saving configuration to .env..."
    cat > "$SCRIPT_DIR/.env" << EOF
# Gitea Pages Configuration
DOMAIN=pages.local
WEBHOOK_SECRET=test-webhook-secret
MAX_SITE_SIZE_MB=50

# Gitea API URL (internal Docker network)
GITEA_API_URL=http://gitea:3000

# Gitea Access Token (auto-generated by test.sh)
GITEA_ACCESS_TOKEN=$GITEA_TOKEN

# OAuth2 Configuration (auto-generated by test.sh)
OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID:-}
OAUTH_CLIENT_SECRET=${OAUTH_CLIENT_SECRET:-}
OAUTH_REDIRECT_URL=http://localhost:8080/oauth/callback
WEBHOOK_PUBLIC_URL=http://deployer:8080/webhook
GITEA_PUBLIC_URL=http://localhost:3000
EOF

    log_success ".env file created"
}

# Create OAuth2 application
create_oauth_app() {
    log_info "Creating OAuth2 application..."

    # Load token from .env if GITEA_TOKEN is not set
    if [ -z "$GITEA_TOKEN" ] && [ -f "$SCRIPT_DIR/.env" ]; then
        GITEA_TOKEN=$(grep "^GITEA_ACCESS_TOKEN=" "$SCRIPT_DIR/.env" | cut -d= -f2)
    fi

    if [ -z "$GITEA_TOKEN" ]; then
        log_error "GITEA_TOKEN not set. Run 'setup-gitea' first"
        return 1
    fi

    local response
    response=$(curl -sf -X POST \
        -H "Content-Type: application/json" \
        -u "testuser:testpassword123" \
        -d '{
            "name": "Gitea Pages",
            "redirect_uris": ["http://localhost:8080/oauth/callback", "http://pages.local:8888/oauth/callback"],
            "confidential_client": true
        }' \
        "http://localhost:3000/api/v1/user/applications/oauth2" 2>&1)

    if echo "$response" | grep -q '"client_id"'; then
        OAUTH_CLIENT_ID=$(echo "$response" | jq -r '.client_id')
        OAUTH_CLIENT_SECRET=$(echo "$response" | jq -r '.client_secret')

        log_success "OAuth2 application created"
        log_info "Client ID: $OAUTH_CLIENT_ID"
        log_info "Client Secret: ${OAUTH_CLIENT_SECRET:0:10}..."

        # Update .env file with OAuth2 credentials
        if [ -f "$SCRIPT_DIR/.env" ]; then
            # Update existing .env
            sed -i.bak "s/^OAUTH_CLIENT_ID=.*/OAUTH_CLIENT_ID=$OAUTH_CLIENT_ID/" "$SCRIPT_DIR/.env" 2>/dev/null || true
            sed -i.bak "s/^OAUTH_CLIENT_SECRET=.*/OAUTH_CLIENT_SECRET=$OAUTH_CLIENT_SECRET/" "$SCRIPT_DIR/.env" 2>/dev/null || true

            # If the lines don't exist, append them
            if ! grep -q "^OAUTH_CLIENT_ID=" "$SCRIPT_DIR/.env" 2>/dev/null; then
                echo "OAUTH_CLIENT_ID=$OAUTH_CLIENT_ID" >> "$SCRIPT_DIR/.env"
                echo "OAUTH_CLIENT_SECRET=$OAUTH_CLIENT_SECRET" >> "$SCRIPT_DIR/.env"
            fi
        fi

        log_success "OAuth2 credentials saved to .env"
    elif echo "$response" | grep -qi "already\|已存在"; then
        log_info "OAuth2 application already exists, fetching existing..."

        # Get existing OAuth2 apps
        local apps
        apps=$(curl -sf -u "testuser:testpassword123" \
            "http://localhost:3000/api/v1/user/applications/oauth2" 2>&1)

        if echo "$apps" | grep -q '"client_id"'; then
            # Get the first Gitea Pages app
            OAUTH_CLIENT_ID=$(echo "$apps" | jq -r '.[0].client_id')
            log_info "Using existing OAuth2 app: $OAUTH_CLIENT_ID"
            log_warning "Client secret not available for existing app. You may need to recreate the OAuth2 app manually."
        fi
    else
        log_warning "Could not create OAuth2 application"
        log_info "Response: $response"
        log_info "You can create it manually at: http://localhost:3000/user/settings/applications"
    fi
}

# Create system-wide webhook (global webhook for all repositories)
create_system_webhook() {
    log_info "Creating system webhook (global)..."

    # Load token from .env if GITEA_TOKEN is not set
    if [ -z "$GITEA_TOKEN" ] && [ -f "$SCRIPT_DIR/.env" ]; then
        GITEA_TOKEN=$(grep "^GITEA_ACCESS_TOKEN=" "$SCRIPT_DIR/.env" | cut -d= -f2)
    fi

    if [ -z "$GITEA_TOKEN" ]; then
        log_error "GITEA_TOKEN not set. Run 'setup-gitea' first or set in .env"
        return 1
    fi

    local response
    response=$(curl -sf -X POST \
        -H "Authorization: Bearer $GITEA_TOKEN" \
        -H "Content-Type: application/json" \
        -d '{
            "type": "gitea",
            "config": {
                "url": "http://deployer:8080/webhook",
                "content_type": "json",
                "secret": "test-webhook-secret"
            },
            "events": ["push", "delete"],
            "active": true
        }' \
        "http://localhost:3000/api/v1/admin/hooks" 2>&1)

    if echo "$response" | grep -q '"id"'; then
        local hook_id=$(echo "$response" | jq -r '.id')
        log_success "System webhook created (ID: $hook_id)"
        log_info "This webhook will trigger for ALL repositories"
    elif echo "$response" | grep -qi "already\|已存在"; then
        log_info "System webhook already exists"
    else
        log_warning "Could not create system webhook, trying repository-level webhook..."
        log_debug "Response: $response"
        # Fallback: create for specific repo
        create_repo_webhook "testuser/test-pages"
    fi
}

# Create webhook for specific repository
create_repo_webhook() {
    local repo=$1
    log_info "Creating webhook for $repo..."

    # Load token from .env if GITEA_TOKEN is not set
    if [ -z "$GITEA_TOKEN" ] && [ -f "$SCRIPT_DIR/.env" ]; then
        GITEA_TOKEN=$(grep "^GITEA_ACCESS_TOKEN=" "$SCRIPT_DIR/.env" | cut -d= -f2)
    fi

    curl -sf -X POST \
        -H "Authorization: Bearer $GITEA_TOKEN" \
        -H "Content-Type: application/json" \
        -d '{
            "type": "gitea",
            "config": {
                "url": "http://deployer:8080/webhook",
                "content_type": "json",
                "secret": "test-webhook-secret"
            },
            "events": ["push", "delete"],
            "active": true
        }' \
        "http://localhost:3000/api/v1/repos/$repo/hooks" > /dev/null

    log_success "Webhook created for $repo"
}

# Restart deployer with new configuration
restart_deployer() {
    log_info "Restarting deployer with new configuration..."

    cd "$SCRIPT_DIR"
    $DOCKER_COMPOSE up -d --build deployer

    log_info "Waiting for deployer to start..."
    sleep 5

    # Check deployer logs
    local logs
    logs=$(docker logs gitea-pages-test-deployer 2>&1 | tail -10)

    if echo "$logs" | grep -q "Gitea Pages Deployer starting"; then
        log_success "Deployer started successfully"

        # Check for auto-register
        if echo "$logs" | grep -q "Auto-register"; then
            echo ""
            log_info "Auto-register output:"
            echo "$logs" | grep "Auto-register" || true
        fi
    else
        log_warning "Deployer may not be ready, check logs"
    fi
}

# Create test repository
create_test_repo() {
    log_info "Creating test repository..."

    # Load token from .env if GITEA_TOKEN is not set
    if [ -z "$GITEA_TOKEN" ] && [ -f "$SCRIPT_DIR/.env" ]; then
        GITEA_TOKEN=$(grep "^GITEA_ACCESS_TOKEN=" "$SCRIPT_DIR/.env" | cut -d= -f2)
    fi

    if [ -z "$GITEA_TOKEN" ]; then
        log_error "GITEA_TOKEN not set"
        return 1
    fi

    local test_repo_dir="$SCRIPT_DIR/test-repo"

    rm -rf "$test_repo_dir"
    mkdir -p "$test_repo_dir"
    cd "$test_repo_dir"

    git init
    git config user.email "test@pages.local"
    git config user.name "Test User"
    git checkout -b gh-pages

    cat > index.html << 'EOF'
<!DOCTYPE html>
<html>
<head>
    <title>Gitea Pages Test</title>
    <style>
        body { font-family: Arial, sans-serif; max-width: 800px; margin: 50px auto; padding: 20px; }
        .success { color: green; }
        .info { background: #f0f0f0; padding: 20px; border-radius: 5px; }
    </style>
</head>
<body>
    <h1>🎉 Gitea Pages Deployment Successful!</h1>
    <div class="info">
        <p><strong>Repository:</strong> testuser/test-pages</p>
        <p><strong>Branch:</strong> gh-pages</p>
        <p><strong>Deployed at:</strong> <span id="time"></span></p>
    </div>
    <script>document.getElementById('time').textContent = new Date().toISOString();</script>
</body>
</html>
EOF

    git add .
    git commit -m "Initial gh-pages content"

    git remote add origin "http://testuser:testpassword123@localhost:3000/testuser/test-pages.git"

    curl -sf -X POST \
        -H "Authorization: Bearer $GITEA_TOKEN" \
        -H "Content-Type: application/json" \
        -d '{"name": "test-pages", "private": false, "auto_init": false}' \
        "http://localhost:3000/api/v1/user/repos" > /dev/null

    log_success "Repository created"

    log_info "Pushing to Gitea..."
    git push -u origin gh-pages --force

    log_success "Content pushed to gh-pages branch"
}

# Create test organization
create_test_org() {
    log_info "Creating test organization..."

    # Load token from .env if GITEA_TOKEN is not set
    if [ -z "$GITEA_TOKEN" ] && [ -f "$SCRIPT_DIR/.env" ]; then
        GITEA_TOKEN=$(grep "^GITEA_ACCESS_TOKEN=" "$SCRIPT_DIR/.env" | cut -d= -f2)
    fi

    if [ -z "$GITEA_TOKEN" ]; then
        log_error "GITEA_TOKEN not set"
        return 1
    fi

    # Create organization
    local org_response
    org_response=$(curl -s -X POST \
        -H "Authorization: Bearer $GITEA_TOKEN" \
        -H "Content-Type: application/json" \
        -d '{
            "username": "testorg",
            "full_name": "Test Organization",
            "description": "Test organization for Gitea Pages",
            "website": "",
            "location": "",
            "visibility": "public"
        }' \
        "http://localhost:3000/api/v1/orgs" 2>&1) || true

    if echo "$org_response" | grep -q '"username"'; then
        log_success "Organization 'testorg' created"
    elif echo "$org_response" | grep -qi "already\|已存在"; then
        log_info "Organization 'testorg' already exists"
    else
        log_warning "Could not create organization: $org_response"
    fi

    # Create organization repository
    log_info "Creating organization repository..."
    local repo_response
    repo_response=$(curl -s -X POST \
        -H "Authorization: Bearer $GITEA_TOKEN" \
        -H "Content-Type: application/json" \
        -d '{"name": "org-site", "private": false, "auto_init": false}' \
        "http://localhost:3000/api/v1/orgs/testorg/repos" 2>&1) || true

    if echo "$repo_response" | grep -q '"name"'; then
        log_success "Organization repository 'testorg/org-site' created"
    elif echo "$repo_response" | grep -qi "already\|已存在"; then
        log_info "Organization repository already exists"
    else
        log_warning "Could not create org repository: $repo_response"
    fi

    # Create and push content to org repo
    local org_repo_dir="$SCRIPT_DIR/org-repo"

    rm -rf "$org_repo_dir"
    mkdir -p "$org_repo_dir"
    cd "$org_repo_dir" || return 1

    git init
    git config user.email "test@pages.local"
    git config user.name "Test User"
    git checkout -b gh-pages

    cat > index.html << 'EOF'
<!DOCTYPE html>
<html>
<head>
    <title>Organization Site - Gitea Pages</title>
    <style>
        body { font-family: Arial, sans-serif; max-width: 800px; margin: 50px auto; padding: 20px; }
        .success { color: green; }
        .info { background: #f0f0f0; padding: 20px; border-radius: 5px; }
        .org-badge { background: #3b82f6; color: white; padding: 4px 8px; border-radius: 4px; font-size: 12px; }
    </style>
</head>
<body>
    <h1>🏢 Organization Site <span class="org-badge">ORG</span></h1>
    <div class="info">
        <p><strong>Organization:</strong> testorg</p>
        <p><strong>Repository:</strong> testorg/org-site</p>
        <p><strong>Branch:</strong> gh-pages</p>
        <p><strong>Deployed at:</strong> <span id="time"></span></p>
    </div>
    <script>document.getElementById('time').textContent = new Date().toISOString();</script>
</body>
</html>
EOF

    git add .
    git commit -m "Initial org site content"

    git remote add origin "http://testuser:testpassword123@localhost:3000/testorg/org-site.git"

    log_info "Pushing to organization repository..."
    git push -u origin gh-pages --force 2>/dev/null || {
        log_warning "Push failed, repository may need manual setup"
    }

    log_success "Organization site pushed"
}

# Verify organization deployment
verify_org_deployment() {
    log_info "Verifying organization deployment..."

    log_info "Waiting for deployment (5 seconds)..."
    sleep 5

    # Check if org repo was deployed
    if docker exec gitea-pages-test-deployer ls /var/www/pages/testorg/org-site/index.html 2>/dev/null; then
        log_success "Organization file deployed successfully!"
    else
        log_info "Organization deployment may need webhook trigger"
    fi

    # Test via nginx
    local response
    response=$(curl -s -H "Host: testorg.pages.local" http://localhost:8888/org-site/ 2>/dev/null) || true

    if echo "$response" | grep -q "Organization Site"; then
        log_success "✅ Organization site is accessible via nginx!"
    else
        log_info "Organization site test (may need OAuth authorization first)"
    fi
}

# Trigger deployment
trigger_deployment() {
    log_info "Triggering deployment..."

    cd "$SCRIPT_DIR/test-repo" || return 1

    echo "<!-- Updated at $(date) -->" >> index.html
    git add index.html
    git commit -m "Trigger deployment"
    git push

    log_info "Waiting for deployment (10 seconds)..."
    sleep 10

    if docker exec gitea-pages-test-deployer ls /var/www/pages/testuser/test-pages/index.html 2>/dev/null; then
        log_success "File deployed successfully!"
    else
        log_warning "Deployment may still be in progress, check logs"
    fi
}

# Verify deployment
verify_deployment() {
    log_info "Verifying deployment..."

    log_info "Testing via nginx (http://localhost:8888)..."

    local response
    response=$(curl -s -H "Host: testuser.pages.local" http://localhost:8888/test-pages/ 2>/dev/null) || true

    if echo "$response" | grep -q "Gitea Pages Deployment Successful"; then
        log_success "✅ Site is accessible via nginx!"
        echo ""
        echo "$response" | grep -o '<title>.*</title>' || true
    else
        log_warning "Site not yet accessible, checking deployer logs..."
        docker logs gitea-pages-test-deployer --tail 20
    fi
}

# Print access info
print_info() {
    echo ""
    echo "=========================================="
    echo -e "${GREEN}Gitea Pages Test Environment Ready!${NC}"
    echo "=========================================="
    echo ""
    echo "📍 Services:"
    echo "   Gitea:     http://localhost:3000"
    echo "   Nginx:     http://localhost:8888"
    echo "   Deployer:  http://localhost:8080"
    echo ""
    echo "👤 Credentials:"
    echo "   Username: testuser"
    echo "   Password: testpassword123"
    echo "   Token:    ${GITEA_TOKEN:0:8}..."
    echo ""
    echo "🔐 OAuth2 Application:"
    echo "   Client ID: ${OAUTH_CLIENT_ID:-<not created>}"
    if [ -n "$OAUTH_CLIENT_SECRET" ]; then
        echo "   Secret:    ${OAUTH_CLIENT_SECRET:0:10}..."
    fi
    echo ""
    echo "🌐 Test Sites (add to /etc/hosts: 127.0.0.1 testuser.pages.local testorg.pages.local pages.local):"
    echo "   Home:      http://pages.local:8888/"
    echo "   Status:    http://pages.local:8888/status"
    echo "   User Root: http://testuser.pages.local:8888/"
    echo "   User Site: http://testuser.pages.local:8888/test-pages/"
    echo "   Org Site:  http://testorg.pages.local:8888/org-site/"
    echo ""
    echo "📝 Add to /etc/hosts:"
    echo "   127.0.0.1 testuser.pages.local testorg.pages.local pages.local"
    echo ""
    echo "🏢 Organization Test:"
    echo "   Organization: testorg"
    echo "   Repository:   testorg/org-site"
    echo ""
    echo "🔧 Useful commands:"
    echo "   Logs:      $DOCKER_COMPOSE -f $SCRIPT_DIR/docker-compose.yml logs -f"
    echo "   Restart:   $DOCKER_COMPOSE -f $SCRIPT_DIR/docker-compose.yml restart"
    echo "   Stop:      $DOCKER_COMPOSE -f $SCRIPT_DIR/docker-compose.yml down"
    echo ""
    echo "📖 OAuth2 Authorization:"
    echo "   1. Visit http://localhost:8080 or http://pages.local:8888"
    echo "   2. Click 'Authorize Gitea Pages'"
    echo "   3. Login and approve"
    echo "   4. Webhooks will be registered for user AND organizations"
    echo "=========================================="
}

# Main function
main() {
    echo ""
    echo "=========================================="
    echo "  Gitea Pages Quickstart Test"
    echo "=========================================="
    echo ""

    check_dependencies

    log_info "Starting services..."
    cd "$SCRIPT_DIR"
    $DOCKER_COMPOSE up -d --build

    wait_for_gitea

    setup_gitea

    create_oauth_app

    create_system_webhook

    restart_deployer

    create_test_repo

    trigger_deployment

    verify_deployment

    create_test_org

    verify_org_deployment

    print_info
}

# Run main or specific function
case "${1:-}" in
    setup-gitea)
        setup_gitea
        ;;
    create-oauth)
        create_oauth_app
        ;;
    create-webhook)
        create_system_webhook
        ;;
    restart-deployer)
        restart_deployer
        ;;
    create-repo)
        create_test_repo
        ;;
    create-org)
        create_test_org
        ;;
    trigger)
        trigger_deployment
        ;;
    verify)
        verify_deployment
        ;;
    verify-org)
        verify_org_deployment
        ;;
    *)
        main
        ;;
esac